# $NetBSD$

PKGNAME=	moonlight-qt-${GIT_TAG:S/v//}
GIT_REPO=	https://github.com/moonlight-stream/moonlight-qt.git
CATEGORIES=	games
GIT_TAG=	v3.1.3

MAINTAINER=	dressupgeekout@gmail.com
COMMENT=	XXX
LICENSE=	gnu-lgpl-v3 # XXX

#BUILD_DEPENDS+=	flex-[0-9]*:../../devel/flex

#USE_LANGUAGES=	c c++
#USE_CMAKE=	yes

.include "../../wip/mk/git-package.mk"
.include "../../mk/bsd.pkg.mk"
